mkdir -p {site/docs/lg,site/docs/md,site/docs/trf,site/docs/lg_vectors,site/docs/md_vectors}
cp huspacy/hu_core_news_md/README.md site/docs/md/index.md 
cp huspacy/hu_core_news_md/CHANGELOG.md site/docs/md/changelog.md 
cp huspacy/hu_core_news_lg/README.md site/docs/lg/index.md 
cp huspacy/hu_core_news_lg/CHANGELOG.md site/docs/lg/changelog.md 
cp huspacy/hu_core_news_trf/README.md site/docs/trf/index.md 
cp huspacy/hu_core_news_trf/CHANGELOG.md site/docs/trf/changelog.md 
cp huspacy/hu_vectors_web_lg/README.md site/docs/lg_vectors/index.md 
cp huspacy/hu_vectors_web_lg/CHANGELOG.md site/docs/lg_vectors/changelog.md
cp huspacy/hu_vectors_web_md/README.md site/docs/md_vectors/index.md 
cp huspacy/hu_vectors_web_md/CHANGELOG.md site/docs/md_vectors/changelog.md
